# Generated by Django 5.0.1 on 2024-10-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_remove_parententity_autogen_author_updated_selectors_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='extendedentity',
            name='entity_exte_autogen_55395d_gin',
        ),
        migrations.RemoveIndex(
            model_name='extendedentity',
            name='entity_exte_autogen_3f6159_gin',
        ),
        migrations.RemoveIndex(
            model_name='extendedentity',
            name='entity_exte_autogen_0a9cf8_gin',
        ),
        migrations.RemoveField(
            model_name='extendedentity',
            name='autogen_author_parent_selectors',
        ),
        migrations.RemoveField(
            model_name='extendedentity',
            name='autogen_author_selectors',
        ),
        migrations.RemoveField(
            model_name='extendedentity',
            name='autogen_author_updated_selectors',
        ),
    ]
