# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 6.1.1 on 2026-10-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "entity",
            "0006_remove_extendedentity_entity_exte_autogen_55395d_gin_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="childentity",
            name="entity_chil_autogen_849c8d_gin",
        ),
        migrations.RemoveIndex(
            model_name="childentity",
            name="entity_chil_autogen_c1a095_gin",
        ),
        migrations.RemoveIndex(
            model_name="childentity",
            name="entity_chil_autogen_eec219_gin",
        ),
        migrations.RemoveIndex(
            model_name="dependententity",
            name="entity_depe_autogen_22be95_gin",
        ),
        migrations.RemoveIndex(
            model_name="dependententity",
            name="entity_depe_autogen_c1c46a_gin",
        ),
        migrations.RemoveIndex(
            model_name="dependententity",
            name="entity_depe_autogen_d06cc8_gin",
        ),
        migrations.RemoveField(
            model_name="childentity",
            name="autogen_author_parent_selectors",
        ),
        migrations.RemoveField(
            model_name="childentity",
            name="autogen_author_selectors",
        ),
        migrations.RemoveField(
            model_name="childentity",
            name="autogen_author_updated_selectors",
        ),
        migrations.RemoveField(
            model_name="dependententity",
            name="autogen_author_parent_selectors",
        ),
        migrations.RemoveField(
            model_name="dependententity",
            name="autogen_author_selectors",
        ),
        migrations.RemoveField(
            model_name="dependententity",
            name="autogen_author_updated_selectors",
        ),
    ]
