# Generated by Django 6.1.1 on 2026-10-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "entity",
            "0006_remove_extendedentity_entity_exte_autogen_55395d_gin_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="childentity",
            name="entity_chil_autogen_849c8d_gin",
        ),
        migrations.RemoveIndex(
            model_name="childentity",
            name="entity_chil_autogen_c1a095_gin",
        ),
        migrations.RemoveIndex(
            model_name="childentity",
            name="entity_chil_autogen_eec219_gin",
        ),
        migrations.RemoveIndex(
            model_name="dependententity",
            name="entity_depe_autogen_22be95_gin",
        ),
        migrations.RemoveIndex(
            model_name="dependententity",
            name="entity_depe_autogen_c1c46a_gin",
        ),
        migrations.RemoveIndex(
            model_name="dependententity",
            name="entity_depe_autogen_d06cc8_gin",
        ),
        migrations.RemoveField(
            model_name="childentity",
            name="autogen_author_parent_selectors",
        ),
        migrations.RemoveField(
            model_name="childentity",
            name="autogen_author_selectors",
        ),
        migrations.RemoveField(
            model_name="childentity",
            name="autogen_author_updated_selectors",
        ),
        migrations.RemoveField(
            model_name="dependententity",
            name="autogen_author_parent_selectors",
        ),
        migrations.RemoveField(
            model_name="dependententity",
            name="autogen_author_selectors",
        ),
        migrations.RemoveField(
            model_name="dependententity",
            name="autogen_author_updated_selectors",
        ),
    ]
