# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 6.1.2 on 2026-10-08 20:01

import bazis.contrib.permit.schemas
import django.db.models.deletion
import model_clone.mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0009_meeting_team'),
        ('users', '0003_user_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time')),
                ('dt_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('nickname', models.CharField(blank=True, max_length=255, verbose_name='Nickname')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model, bazis.contrib.permit.schemas.PermitStructMixin),
        ),
        migrations.AddField(
            model_name='meeting',
            name='guest_teams',
            field=models.ManyToManyField(blank=True, related_name='guest_meetings', to='entity.team', verbose_name='Guest teams'),
        ),
    ]
