# Generated by Django 5.0.1 on 2024-11-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='groups', to='permit.permission', verbose_name='Permissions'),
        ),
    ]
