# Generated by Django 5.0.9 on 2025-03-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0002_alter_grouppermission_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='slug',
            field=models.TextField(unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='slug',
            field=models.TextField(unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.TextField(unique=True, verbose_name='Label'),
        ),
    ]
