# Generated by Django 5.0.14 on 2025-10-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0003_alter_grouppermission_slug_alter_permission_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='slug',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='slug',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
