# Generated by Django 5.0.1 on 2025-12-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0004_alter_grouppermission_slug_alter_permission_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='slug',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='slug',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Label'),
        ),
    ]
