# Generated by Django 5.0.1 on 2025-12-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0005_alter_grouppermission_slug_alter_permission_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppermission',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='grouppermission',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
    ]
