# Generated by Django 6.1.1 on 2026-10-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permit", "0006_remove_grouppermission_name_remove_role_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouppermission",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
    ]
