# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 6.1.1 on 2026-10-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permit", "0006_remove_grouppermission_name_remove_role_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouppermission",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
    ]
